### PR TITLE
BI-13524: Consume stream company profile messages

### PR DESCRIPTION
**Pull request by VaughanJackson123**
- Use [consumer-maven-archetype](https://github.com/companieshouse/consumer-maven-archetype) generated code as basis of resilient consumer implementation.
- Mandate environment variables required to configure the resulting consumer.
- Get message consumer to call a service that logs the message clearly, and that will eventually send HTTP requests to the Search API to update the alphabetical ElasticSearch index.
- Manually test and verify successful resilient consumption (in development).
- Include a Postman request to test the message consumption within the context of the streaming architecture, by sending a `resource-changed` notification via the `chs-kafka-api`.
- Also include a manual in Tilt test producer of `stream-company-profile` messages to test the consumption more directly.

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by rmcmurray-ch — APPROVED** [review]
- builds successfully locally
- tilts up successfully
- health check returns 200 OK
- trigger company profile update POST returns 201 created and appears in alphabetical-company-search-consumer logs
- stream-company-profile message produces to tilt

**Comment by ch-code-analysis** [comment]
CI: Security warnings found!

**Pull request merged**
